2023-12-05 07:42:37,627 INFO    StreamThr :33566 [internal.py:wandb_internal():86] W&B internal server running at pid: 33566, started at: 2023-12-05 07:42:37.625327
2023-12-05 07:42:37,630 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status
2023-12-05 07:42:37,636 INFO    WriterThread:33566 [datastore.py:open_for_write():85] open: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/run-7835956g.wandb
2023-12-05 07:42:37,638 DEBUG   SenderThread:33566 [sender.py:send():380] send: header
2023-12-05 07:42:37,657 DEBUG   SenderThread:33566 [sender.py:send():380] send: run
2023-12-05 07:42:38,467 INFO    SenderThread:33566 [dir_watcher.py:__init__():211] watching files in: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files
2023-12-05 07:42:38,468 INFO    SenderThread:33566 [sender.py:_start_run_threads():1122] run started: 7835956g with start time 1701762157.627629
2023-12-05 07:42:38,518 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: check_version
2023-12-05 07:42:38,519 DEBUG   SenderThread:33566 [sender.py:send_request():407] send_request: check_version
2023-12-05 07:42:38,795 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: run_start
2023-12-05 07:42:38,819 DEBUG   HandlerThread:33566 [system_info.py:__init__():32] System info init
2023-12-05 07:42:38,819 DEBUG   HandlerThread:33566 [system_info.py:__init__():47] System info init done
2023-12-05 07:42:38,819 INFO    HandlerThread:33566 [system_monitor.py:start():181] Starting system monitor
2023-12-05 07:42:38,820 INFO    SystemMonitor:33566 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-12-05 07:42:38,820 INFO    HandlerThread:33566 [system_monitor.py:probe():201] Collecting system info
2023-12-05 07:42:38,822 INFO    SystemMonitor:33566 [interfaces.py:start():190] Started cpu monitoring
2023-12-05 07:42:38,823 INFO    SystemMonitor:33566 [interfaces.py:start():190] Started disk monitoring
2023-12-05 07:42:38,830 INFO    SystemMonitor:33566 [interfaces.py:start():190] Started gpu monitoring
2023-12-05 07:42:38,831 INFO    SystemMonitor:33566 [interfaces.py:start():190] Started memory monitoring
2023-12-05 07:42:38,832 INFO    SystemMonitor:33566 [interfaces.py:start():190] Started network monitoring
2023-12-05 07:42:38,939 DEBUG   HandlerThread:33566 [system_info.py:probe():196] Probing system
2023-12-05 07:42:38,945 DEBUG   HandlerThread:33566 [system_info.py:_probe_git():181] Probing git
2023-12-05 07:42:38,967 DEBUG   HandlerThread:33566 [system_info.py:_probe_git():189] Probing git done
2023-12-05 07:42:38,967 DEBUG   HandlerThread:33566 [system_info.py:probe():244] Probing system done
2023-12-05 07:42:38,967 DEBUG   HandlerThread:33566 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-78-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2023-12-05T07:42:38.939649', 'startedAt': '2023-12-05T07:42:37.598666', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/yishido/self_supervied/notpredictor_vit.py', 'codePathLocal': 'notpredictor_vit.py', 'codePath': 'notpredictor_vit.py', 'git': {'remote': 'git@github.com:yuzuki-lab/self-supervised.git', 'commit': 'c441728209ccdd4671d6a297411fd3e05f4d9551'}, 'email': '117724724+yuzuki-lab@users.noreply.github.com', 'root': '/home/yishido/self_supervied', 'host': 'mach01', 'username': 'yishido', 'executable': '/home/yishido/.pyenv/versions/3.10.12/bin/python', 'cpu_count': 32, 'cpu_count_logical': 32, 'cpu_freq': {'current': 1802.79028125, 'min': 1500.0, 'max': 3000.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3296.887, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3000.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2394.322, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1498.463, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 2400.0, 'min': 1500.0, 'max': 3000.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3000.0}, {'current': 3295.379, 'min': 1500.0, 'max': 3000.0}], 'disk': {'/': {'total': 1876.7089385986328, 'used': 73.20025253295898}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 251.74816131591797}}
2023-12-05 07:42:38,968 INFO    HandlerThread:33566 [system_monitor.py:probe():211] Finished collecting system info
2023-12-05 07:42:38,968 INFO    HandlerThread:33566 [system_monitor.py:probe():214] Publishing system info
2023-12-05 07:42:38,968 DEBUG   HandlerThread:33566 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-05 07:42:38,971 DEBUG   HandlerThread:33566 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-05 07:42:38,974 INFO    HandlerThread:33566 [system_monitor.py:probe():216] Finished publishing system info
2023-12-05 07:42:39,005 DEBUG   SenderThread:33566 [sender.py:send():380] send: files
2023-12-05 07:42:39,005 INFO    SenderThread:33566 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-12-05 07:42:39,027 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:39,031 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:39,032 DEBUG   SenderThread:33566 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:39,472 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/wandb-metadata.json
2023-12-05 07:42:39,473 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/requirements.txt
2023-12-05 07:42:39,497 DEBUG   SenderThread:33566 [sender.py:send():380] send: telemetry
2023-12-05 07:42:39,858 INFO    wandb-upload_0:33566 [upload_job.py:push():131] Uploaded file /tmp/tmpusox4u3iwandb/21uuu358-wandb-metadata.json
2023-12-05 07:42:43,499 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:48,499 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:50,485 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/output.log
2023-12-05 07:42:52,488 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/output.log
2023-12-05 07:42:53,772 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:42:54,028 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:42:54,029 DEBUG   SenderThread:33566 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:42:54,030 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:42:58,495 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/output.log
2023-12-05 07:42:59,290 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:04,291 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:05,968 ERROR   FileStreamThread:33566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/a_citrus/SimSiam/7835956g/file_stream
NoneType: None
2023-12-05 07:43:06,507 INFO    Thread-12 :33566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/files/output.log
2023-12-05 07:43:09,033 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: internal_messages
2023-12-05 07:43:09,038 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: stop_status
2023-12-05 07:43:09,038 DEBUG   SenderThread:33566 [sender.py:send_request():407] send_request: stop_status
2023-12-05 07:43:10,254 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: status_report
2023-12-05 07:43:10,451 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:10,451 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:11,800 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:11,801 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:14,417 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:14,418 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:14,418 INFO    SenderThread:33566 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-12-05 07:43:18,069 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: poll_exit
2023-12-05 07:43:18,938 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:18,938 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:23,072 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:27,986 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:27,986 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:28,074 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:33,077 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:38,079 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:38,833 DEBUG   SystemMonitor:33566 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-12-05 07:43:43,082 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:47,794 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:43:47,794 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:43:48,084 DEBUG   HandlerThread:33566 [handler.py:handle_request():144] handle_request: keepalive
2023-12-05 07:43:48,907 INFO    memory    :33566 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2023-12-05 07:43:48,908 DEBUG   SystemMonitor:33566 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-12-05 07:43:48,909 DEBUG   SystemMonitor:33566 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-12-05 07:43:50,708 WARNING StreamThr :33566 [internal.py:is_dead():414] Internal process exiting, parent pid 33449 disappeared
2023-12-05 07:43:50,709 ERROR   StreamThr :33566 [internal.py:wandb_internal():152] Internal process shutdown.
2023-12-05 07:43:50,918 INFO    HandlerThread:33566 [handler.py:finish():844] shutting down handler
2023-12-05 07:43:50,919 INFO    HandlerThread:33566 [system_monitor.py:finish():190] Stopping system monitor
2023-12-05 07:43:50,919 INFO    HandlerThread:33566 [interfaces.py:finish():202] Joined cpu monitor
2023-12-05 07:43:50,919 INFO    HandlerThread:33566 [interfaces.py:finish():202] Joined disk monitor
2023-12-05 07:43:50,920 INFO    WriterThread:33566 [datastore.py:close():294] close: /home/yishido/self_supervied/wandb/run-20231205_074237-7835956g/run-7835956g.wandb
2023-12-05 07:43:50,920 INFO    HandlerThread:33566 [interfaces.py:finish():202] Joined gpu monitor
2023-12-05 07:43:50,921 INFO    HandlerThread:33566 [interfaces.py:finish():202] Joined memory monitor
2023-12-05 07:43:50,922 INFO    HandlerThread:33566 [interfaces.py:finish():202] Joined network monitor
2023-12-05 07:44:23,981 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:44:23,982 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:45:36,101 ERROR   SenderThread:33566 [internal_api.py:execute():369] 409 response executing GraphQL.
2023-12-05 07:45:36,102 ERROR   SenderThread:33566 [internal_api.py:execute():370] {"errors":[{"message":"run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-05 07:45:36,103 ERROR   StreamThr :33566 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2007, in upsert_run
    response = self.gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 538, in debounce
    self._maybe_update_config(always=final)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 515, in _maybe_update_config
    self._debounce_config()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 544, in _debounce_config
    self._api.upsert_run(
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run a_citrus/SimSiam/7835956g was previously created and deleted; try a new run name (Error 409: Conflict)
