Files already downloaded and verified
Data loaded: there are 5000 train images.
Starting training !
Traceback (most recent call last):
  File "/home/yishido/self_supervied/test.py", line 216, in <module>
    main()
  File "/home/yishido/self_supervied/test.py", line 179, in main
    loss = train(train_loader,model,device,criterion,optimizer)
  File "/home/yishido/self_supervied/test.py", line 209, in train
    train_losses += loss.items()
AttributeError: 'Tensor' object has no attribute 'items'