Files already downloaded and verified
Data loaded: there are 5000 train images.
Starting training !
--------------------------------------------------------------------------------------------
0epoch
Loss: -0.13156743347644806
Traceback (most recent call last):
  File "/home/yishido/self_supervied/test.py", line 216, in <module>
    main()
  File "/home/yishido/self_supervied/test.py", line 179, in main
    loss = train(train_loader,model,device,criterion,optimizer)
  File "/home/yishido/self_supervied/test.py", line 198, in train
    for images, _ in train_loader:
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt