
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Data loaded: there are 5000 train images.
Starting training !
Traceback (most recent call last):
  File "/home/yishido/self_supervied/notpredictor_resnet.py", line 311, in <module>
    main()
  File "/home/yishido/self_supervied/notpredictor_resnet.py", line 213, in main
    loss = train(Train_loader,model,device,criterion,optimizer)
  File "/home/yishido/self_supervied/notpredictor_resnet.py", line 239, in train
    p1, p2, z1, z2 = model(x1=im_1, x2=im_2)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yishido/self_supervied/notpredictor_resnet.py", line 88, in forward
    p1 = self.encoder(z1) # NxC
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/yishido/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 2048]